# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-15 18:55
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EcoCase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ecocase_title', models.CharField(max_length=200)),
                ('ecocase_promise', models.CharField(max_length=500)),
                ('ecocase_usage', models.CharField(max_length=500)),
                ('ecocase_organization', models.CharField(max_length=500)),
                ('ecocase_economic_trans', models.CharField(max_length=200)),
                ('ecocase_ref', models.CharField(max_length=20)),
                ('ecocase_direct_envtal_gain', models.BooleanField()),
                ('ecocase_indirect_envtal_gain', models.BooleanField()),
                ('ecocase_proven', models.CharField(max_length=10)),
                ('ecocase_attractive_price', models.BooleanField()),
                ('ecocase_image_urls', models.CharField(default='', max_length=2000)),
                ('ecocase_images', models.FileField(null=True, upload_to='ecocases')),
                ('timestamp', models.DateTimeField(null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ESM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('esm_title', models.CharField(max_length=100)),
                ('esm_file', models.FileField(null=True, upload_to='esms')),
                ('votes', models.IntegerField(default=0)),
                ('ecocase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecocases.EcoCase')),
            ],
        ),
    ]
