# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-15 23:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecocases', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ecocase',
            old_name='ecocase_attractive_price',
            new_name='attractiveness_price',
        ),
        migrations.RenameField(
            model_name='ecocase',
            old_name='ecocase_direct_envtal_gain',
            new_name='direct_environmental_gain',
        ),
        migrations.RenameField(
            model_name='ecocase',
            old_name='ecocase_economic_trans',
            new_name='economic_trans',
        ),
        migrations.RenameField(
            model_name='ecocase',
            old_name='ecocase_image_urls',
            new_name='image_urls',
        ),
        migrations.RenameField(
            model_name='ecocase',
            old_name='ecocase_images',
            new_name='images',
        ),
        migrations.RenameField(
            model_name='ecocase',
            old_name='ecocase_indirect_envtal_gain',
            new_name='indirect_environmental_gain',
        ),
        migrations.RenameField(
            model_name='ecocase',
            old_name='ecocase_organization',
            new_name='organization',
        ),
        migrations.RenameField(
            model_name='ecocase',
            old_name='ecocase_promise',
            new_name='promise',
        ),
        migrations.RenameField(
            model_name='ecocase',
            old_name='ecocase_ref',
            new_name='reference',
        ),
        migrations.RenameField(
            model_name='ecocase',
            old_name='ecocase_title',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='ecocase',
            old_name='ecocase_usage',
            new_name='usage',
        ),
        migrations.RemoveField(
            model_name='ecocase',
            name='ecocase_proven',
        ),
        migrations.AddField(
            model_name='ecocase',
            name='proven_cas_or_project',
            field=models.CharField(choices=[('project', 'Project'), ('proven cas', 'Proven cas')], default='project', max_length=20),
        ),
    ]
