# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-15 23:22
from __future__ import unicode_literals

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('ecocases', '0002_auto_20171015_2302'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ecocase',
            name='economic_trans',
        ),
        migrations.AddField(
            model_name='ecocase',
            name='economic_transaction',
            field=tinymce.models.HTMLField(default=''),
        ),
        migrations.AlterField(
            model_name='ecocase',
            name='organization',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='ecocase',
            name='promise',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='ecocase',
            name='reference',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='ecocase',
            name='usage',
            field=tinymce.models.HTMLField(),
        ),
    ]
