# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-15 23:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecocases', '0003_auto_20171015_2322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ecocase',
            name='attractiveness_price',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='ecocase',
            name='direct_environmental_gain',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='ecocase',
            name='indirect_environmental_gain',
            field=models.NullBooleanField(),
        ),
    ]
