# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-16 00:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecocases', '0004_auto_20171015_2330'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='esm',
            name='esm_file',
        ),
        migrations.RemoveField(
            model_name='esm',
            name='esm_title',
        ),
        migrations.AddField(
            model_name='esm',
            name='esm_type',
            field=models.IntegerField(default=1),
        ),
    ]
