# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-18 09:05
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecocases', '0007_auto_20171017_1802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ecocase',
            name='reference',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='vote',
            name='vote_point',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(16), django.core.validators.MinValueValidator(0)]),
        ),
    ]
