# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-18 09:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecocases', '0008_auto_20171018_0905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ecocase',
            name='image_urls',
            field=models.CharField(default='', max_length=2000, null=True),
        ),
    ]
